### PR TITLE
Redesign VPS view and organise it with cards

### PR DESCRIPTION
**Pull request by Libter**

### CODE REVIEW

**Comment by SystemZ** [comment]
Currently this doesn't start on `npm run dev`, can you check it out?

```plain
webpack: Compiled successfully.
error during render : /
TypeError: bind is not a function
    at Config (__vue_ssr_bundle__:25904:10)
    at plugin (__vue_ssr_bundle__:26720:3)
    at Function.Vue.use (__vue_ssr_bundle__:8495:14)
    at Object.<anonymous> (__vue_ssr_bundle__:22182:54)
    at __webpack_require__ (__vue_ssr_bundle__:21:30)
    at Object.<anonymous> (__vue_ssr_bundle__:38355:63)
    at __webpack_require__ (__vue_ssr_bundle__:21:30)
    at __vue_ssr_bundle__:67:18
    at Object.<anonymous> (__vue_ssr_bundle__:70:10)
    at evaluateModule (/some_dir/spawn-frontend-material/node_modules/vue-server-renderer/build.js:6820:21)
```

**Comment by Libter** [comment]
I was starting with command `node server`, but it's the same effect as `"dev": "HOST=0.0.0.0 NODE_ENV=development node server"`. Try running `npm install` before start.

**Comment by SystemZ** [comment]
Still no luck, maybe my deps are newer than yours, try deleting node_modules and then `npm install` too.

**Comment by SystemZ** [comment]
After clean npm install on master, same problem, so it's not this merge fault.
It must be deps.

**Comment by SystemZ** [comment]
Whoaa, this new look is awesome!

**Pull request merged**
